##
##  To test this workflow: 
##  1. Run it a first time
##  2. After a few seconds and when the first run is in progress, run it a second time 
##  3. The first run which is in progress should be stopped and the second should start
##

name: "Concurrency - Maximum one workflow concurrently running"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.workflow }}-${{ github.ref }}"
      - run: sleep 60s
