name: 'Custom actions - Testing a container action'

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Using custom container action
        id: greeting-message
        uses: felipeleonfernandez/simple-custom-container-action@main
        with:
          name: Felipe
      - run: echo ${{ steps.greeting-message.outputs.msg }}
