name: Create and Push Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v1.0.0)'
        required: true

permissions:
  contents: write  # Grants permission to push tags

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.


      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and Push Tag with PAT
        env:
          PAT: ${{ secrets.PAT }}  # Use a personal access token instead of GITHUB_TOKEN
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }}.git ${{ github.event.inputs.tag }}