name: "Simple workflow that runs on every push"

on:
  push:
    paths-ignore:
      ## Will ignore push events that modify something in .github folder,
      ## even if there are changes in other paths
      - '.github/**'

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
