name: 'Triggering - Run a workflow with the context of the compare branch'

on:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World! I ran because a pull request was opened and I have the context of the compare branch"
      - name: Checkout code
        uses: actions/checkout@v2
      - run: ls -l
